// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "expense-app-20181113-hosting",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://expense-app-20181113-hosting.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:3100247b-6ec7-4587-bbc3-12116ed550b1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ynBs7M3xV",
    "aws_user_pools_web_client_id": "6u2375mt5tqflsor2ggb2j6b04",
    "aws_appsync_graphqlEndpoint": "https://co4hltpzerf2ve3t4s25lrnl44.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
