// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "expenseapp-20181114102808--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://expenseapp-20181114102808--hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:f1103dd2-aa42-4966-a13b-b5ca5a1db2ed",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_664L9gHAy",
    "aws_user_pools_web_client_id": "iduqn34m2jc1fmg83fcv7umk8",
    "aws_appsync_graphqlEndpoint": "https://3kxl3c5yv5fxrm5alh6bjda54e.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
