// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "expenseapp-20181014165038--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://expenseapp-20181014165038--hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:af4b08d5-df98-48df-9410-0fc23b07a5bc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Sm6V7MSxL",
    "aws_user_pools_web_client_id": "56nutdh6c9d73tjoo9jq7ork06"
};


export default awsmobile;
